### ISSUE TITLE
Update links to heat templates in Developer Guide

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-orchestration#25]
Raj Patel reported the following issue in the [docs-quickstart](https://github.com/rackerlabs/docs-cloud-orchestration/issues] repo.  Moving here so the Orchestration source docs can be updated. 

In cloud orchestration dev guide, there is a link for getting latest templates https://github.com/rackspace-heat-templates. The link is incorrect and it should point to https://github.com/rackspace-orchestration-templates/

**Comment by masthalter** [comment]
Corrected link and republished Orchestration Devguide
