### ISSUE TITLE
Edits for release notes

### ISSUE THREAD

**Issue by kmsholcomb** [rackerlabs/docs-cloud-orchestration#26]
See the markup and comments in the attached Word doc for my suggested edits for the release notes. Please let me know if you have any questions. Thanks!

[Cloud Orchestration Release Notes_editsKH.docx](https://github.com/rackerlabs/docs-cloud-orchestration/files/30181/Cloud.Orchestration.Release.Notes_editsKH.docx)

**Comment by masthalter** [comment]
I've done your edits and published.

Thanks!

Mike
