### ISSUE TITLE
Updates to Cloud Getting Started Guide content

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-orchestration#28]
Took a look at the migrated GS content these are the things that need fixing:

- Change the title that shows up in the Navigation to **Getting Started** -- so that it shows up bold in the    navigation 
 [DONE, Mike]

- Revise the Getting Started intro paragraphs to read like the one in Cloud Queues: https://developer.rackspace.com/docs/cloud-queues/v1/developer-guide/#getting-started
 [DONE, Mike]

- Missing Authenticate by using the heat client topic.
 [DONE, Mike]

-  In the General API section, change the authentication file to authentication-ovw.rst. Replace the text with the content described in the GS migration instructions: [Update authentication section in general api section](https://github.com/rackerlabs/docs-common/tree/master/rst/getting-started-content-architecture#update-authentication-section-in-general-api-info-section)
[DONE, Mike]

- In the Using Orchestration topic, revise the intro so it is relevant to the Cloud Orchestration API documentation.  The text there fits with the Cloud Queues documentation which has sections about the API workflow and use cases.  Orchestration doesn't have those.
 [DONE, Mike]

- For all of the examples, change the heading level of the client and cURL examples so they don't show up in the TOC. 

 ```
 .. _create-stack-heat:

Client Example
^^^^^^^^^^^^^^^^^

...
 .. _create-stack-curl:

  cURL example
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 ```
[DONE, Mike]

- Fix table for showing results of stack-show CLI command output in section "Show stack details by using the heat client". Probably need to format as code rather than table.
[DONE, Mike]

- Fix table for showing results of stack-update CLI command output in section "Update a stack with a load balancer by using the heat client". Probably need to format as code rather than table.
[DONE, Mike]

**Comment by meker12** [comment]
Another small change in the common-gs/get-credentials.rst common topic.  

Change the labels for *Save API key* and *Save account* number to heading level 3 titles.

**Comment by meker12** [comment]
Authenticate by using the client topic is missing.

**Comment by masthalter** [comment]
I have addressed all of your comments, Margaret, so I'm closing this issue.

Mike
