### ISSUE TITLE
Docs project updates

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-orchestration#35]
- [x] Add disclaimer to Developer Docs [Trello card] (https://trello.com/c/mC8WjS05)

- [x] Update _deconst.json to add variables to enable **Edit on GitHub** feature [Trello card](https://trello.com/c/U7m8RsvU)

- [x] Remove SLA and pricing topic from docs [Trello card](https://trello.com/c/lzxa1vx2/3206-remove-sla-and-pricing-from-devdocs)

**Comment by cyrichardson** [comment]
PRs #43  #44  #41
