### ISSUE TITLE
Update contributor collateral

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-orchestration#49]
Kelly edited the contributor collateral, and we added a CONTRIBUTING.md so that users get the link to contributor instructions when working in the repo.

Using [Cloud Identity](https://github.com/rackerlabs/docs-cloud-identity] as a model, update the info for contributors:

 - [x] Revise README.md
 - [x] Add CONTRIBUTING.md
 - [x] Add GITHUBING.md

Update all links and naming to match product.

**Comment by kylelaffoon** [comment]
Updated https://github.com/rackerlabs/docs-cloud-orchestration/blob/master/README.md
Added https://github.com/rackerlabs/docs-cloud-orchestration/blob/master/CONTRIBUTING.md

**Comment by kylelaffoon** [comment]
May need to reopen branch to complete Githubing addition. Checking with @meker12.

**Comment by kylelaffoon** [comment]
Added https://github.com/rackerlabs/docs-cloud-orchestration/blob/master/GITHUBING.md
