### ISSUE TITLE
QE refactored Cloud Orchestration content

### ISSUE THREAD

**Issue by meker12** [rackerlabs/docs-cloud-orchestration#58]
# Refactor API Guide: QE checklist

Use the following checklist to verify that API guide refactoring for each service. If you have questions, open a [docs-common issue](https://github.com/rackerlabs/docs-common/issues/new).  

Do the QE check against the PR submitted to the master repo.  Ask the person who did the refactoring to make you a collaborator on their fork in case you want to submit a PR to correct something. 

When you build the refactored Sphinx project, use the ``make clean html`` command to build chunked content. 

- [x] Review the [Strider build log](https://build.developer.rackspace.com/) for errors. Notify author about any issues.
- [x] Check for broken links.
- [x] Verify that navigation matches the [API Guide template](https://staging.developer.rackspace.com/staging.horse/build-2ecafb8a99/docs/api-doc-template/).
- [x] Check the *API reference* section to verify that the methods for each resource are in a single topic.
- [x] Check the *General API information* topics to make sure they match the common content where possible.
- [x] Check the *Authentication* topic in the Getting started section to make sure it matches the [common template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/getting-started/authenticate.rst).
- [x] Check ``conf.py`` to make sure it has the updates from the 
       [template](https://github.com/rackerlabs/docs-common/blob/master/api-guide-template/conf.py).
- [x] Verify that you can [build locally from source](https://github.com/rackerlabs/docs-rackspace/blob/master/doc/tools/build-from-source.rst).

**Comment by catlook** [comment]
Strider build has one warning, which I've seen many times and which appears not to matter.  Just noting it here: ./getting-started/authenticate.rst:1: WARNING: Could not lex literal_block as "json". Highlighting skipped.
writing output... [100%] service-updates

**Comment by catlook** [comment]
Broken link "For additional information about authentication errors, see the Identity API Reference documentation." Right before configure environment variables.

**Comment by catlook** [comment]
This looks odd to me: https://staging.developer.rackspace.com/build-b6caab2ecf/docs/cloud-orchestration/v1/developer-guide/getting-started/using-cloud-orchestration/#update-a-stack-with-a-load-balancer-by-using-curl   The bullet list seems malformed.

**Comment by catlook** [comment]
This looks odd to me: https://staging.developer.rackspace.com/build-b6caab2ecf/docs/cloud-orchestration/v1/developer-guide/getting-started/using-cloud-orchestration/#update-a-stack-with-a-load-balancer-by-using-curl   The bullet list seems malformed.

**Comment by catlook** [comment]
Wrong link at teh end of rbac: API operations for Cloud Orchestration may or may not be available to all roles. To see which operations are permitted to invoke which calls, please review the Permissions Matrix for Next Generation Cloud Servers.   points to next gen server matrix instead of orchestration matrix

**Comment by catlook** [comment]
At the start of the API reference, looks like things are duplicated:  
You can use the Cloud Orchestration API operations to interact directly with the service. You can also complete the operations using the heat client, the Rackspace Command Line Interface (rack CLI), one of the language-specific software development kits, or the Cloud Control Panel.

tip: You can also perform operations by using the Rackspace Command Line Interface (rack CLI), one of the language-specific software development kits, or the Cloud Control Panel.

**Comment by catlook** [comment]
the template has service updates before additional resources. The orch guide reverses those.

**Comment by catlook** [comment]
General API has Paginated collections before date and time, orch guide reverses them.

**Comment by catlook** [comment]
Authentication section differed a bit in content with the addition of heat authentication, but also in various heading levels.

**Comment by catlook** [comment]
conf.py: 
missing author = 'Rackspace' (line 71 in common would be 73 in orch)
exclude patterns are different (line 97 in common)
rax-devguide (lin 126 in orch) should be deleted
html_use_smartypants is set to false in orch and true in common (line 219).  maybe that's on purpose?
LIkewise html_add_permalinks = '#' (line 272) is missing in orch
orch has ['Rackspace'] instead of 'Rackspace' in textinfo_documents section (line 337 in orch)

**Comment by catlook** [comment]
local build good, and review complete!  Let me know if you have any questions :)

**Comment by meker12** [comment]
Applied changes and merged in PR #57.
